version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 8000
    volumes:
      - .:/NewsArticle
    ports:
      - "8000:8000"
    depends_on:
      - db
